<?php
/******************************************************************************
 *
 *	 COMPANY: Intelliants LLC
 *	 PROJECT: eSyndiCat Directory Software
 *	 VERSION: 3.3.0
 *	 LISENSE: http://www.esyndicat.com/license.html
 *	 http://www.esyndicat.com/
 *
 *	 This program is a commercial software and any kind of using it must agree 
 *	 to eSyndiCat Directory Software license.
 *
 *	 Link to eSyndiCat.com may not be removed from the software pages without
 *	 permission of eSyndiCat respective owners. This copyright notice may not
 *	 be removed from source code in any case.
 *
 *	 Copyright 2007-2013 Intelliants LLC
 *	 http://www.intelliants.com/
 *
 ******************************************************************************/

global $esynConfig;
$last_check = $esynConfig->getConfig('cron_backup_last_time') + ($esynConfig->getConfig('cron_backup_interval')*24*60*60) - time();
if (!$esynConfig->getConfig('cron_backup') || $last_check > 0) return false;

$out  = "#  MySQL COMMON INFORMATION:\n";
$out .= "#  MySQL CLIENT INFO: ".mysql_get_client_info()."\n";
$out .= "#  MySQL HOST INFO: ".mysql_get_host_info()."\n";
$out .= "#  MySQL PROTOCOL VERSION: ".mysql_get_proto_info()."\n";
$out .= "#  MySQL SERVER VERSION: ".mysql_get_server_info()."\n\n";
$out .= "#  __MySQL DUMP GENERATED BY ESYNDICAT__ #"."\n";
$out .= "\n\n";
$out .= 'SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";' . "\n\n";

if ($esynConfig->getConfig('cron_backup_archive') && extension_loaded('zlib'))
	$fname = 'compress.zlib://' . IA_HOME . 'backup/' . date('mdy') . '.sql.gz';
else
	$fname = IA_HOME . 'backup/' . date('mdy') . '.sql';

$file = fopen($fname, 'w');

if ($file)
{
	fwrite($file, $out);

	$tables = $eSyndiCat->getAssoc("SHOW TABLES LIKE '{$eSyndiCat->mPrefix}%'");
	$tables = array_keys($tables);

	foreach ($tables as $t)
	{
		// TABLE STRUCTURE
		$res = $eSyndiCat->getRow("SHOW CREATE TABLE `$t`");
		$out = $res ? "\n" . array_pop($res) . ";\n" : false;
		fwrite($file, $out);

		// TABLE DATA
		$start = 0;
		$limit = 50;
		$eSyndiCat->setTable(substr($t, strlen($eSyndiCat->mPrefix)));
		while($data = $eSyndiCat->all('*', 1, false, $start, $limit))
		{
			$start += $limit;
			$out = "INSERT INTO `$t` VALUES " . PHP_EOL;
			foreach ($data as $d)
			{
				$d = array_values($d);
				$d = array_map('mysql_real_escape_string', $d);

				$out .= "('" . implode("', '", $d) . "'),\n";
			}
			$out = substr($out, 0, -2) . ";\n";
			fwrite( $file, $out );
		}
	}
	fclose($file);
	$esynConfig->setConfig('cron_backup_last_time', time(), true);
}
